

spring:
  profiles:
    active: ${profile}
  jpa:
    hibernate:
      ddl_auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
#        show_sql : true
#        format_sql: true
#        use_sql_comments: true
    database-platform: org.hibernate.dialect

  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: "/static/**"




mybatis:
  type-aliases-package: com.web.board
  mapper-locations: com.web.board.mapper/*.xml

  # show sql data binding
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    jdbc:
      sql only: off
      sliding: info
      result-settable: info
      audit: off
      result: off
      connection: off
      




