

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${test.url}
    username: ${test.id}
    password: ${test.pw}
  jpa:
    hibernate:
      ddl_auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql : true
        format_sql: true
        use_sql_comments: true

  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  type-aliases-package: com.web.board
  mapper-locations: com.web.board.mapper/*.xml

  # show sql data binding
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    jdbc:
      sql only: off
      sliding: info
      result-settable: info
      audit: off
      result: off
      connection: off


