

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${test.url}
    username: ${test.id}
    password: ${test.pw}





#AWS S3 설정
cloud:
  aws:
    credentials:
      access-key: ${awsUser.key}
      secret-key: ${awsUserSecreat.key}
    s3:
      bucket: toyproject-burket
    region:
      static: ap-northeast-2
    stack:
      auto: false



